# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoSeQuePedo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AñadirUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
