# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoSeQuePedo', '0002_añadirusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AñadirUsuario',
        ),
    ]
