# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoSeQuePedo', '0003_delete_añadirusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AñadirUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombrazo', models.CharField(max_length=31)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=30)),
            ],
        ),
    ]
