# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NoSeQuePedo', '0005_publicaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='añadirusuarios',
            name='Ciudad_Actual',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='añadirusuarios',
            name='Ciudad_Origen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='añadirusuarios',
            name='Edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='añadirusuarios',
            name='FechaNac',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='añadirusuarios',
            name='Ocupacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='añadirusuarios',
            name='Sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='añadirusuarios',
            name='Telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='horaPublic',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
