# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoSeQuePedo', '0007_remove_añadirusuarios_ciudad_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='añadirusuarios',
            name='Ciudad_Actual',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
