# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoSeQuePedo', '0008_añadirusuarios_ciudad_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='añadirusuarios',
            name='Ciudad_Actual',
        ),
    ]
