# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoSeQuePedo', '0010_añadirusuarios_ciudad_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='añadirusuarios',
            name='Sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, null=True),
        ),
    ]
