# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoSeQuePedo', '0012_auto_20171129_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='añadirusuarios',
            name='Sexo',
        ),
    ]
