# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoSeQuePedo', '0013_remove_añadirusuarios_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='añadirusuarios',
            name='ultimoAcceso',
            field=models.DateTimeField(null=True),
        ),
    ]
