# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NoSeQuePedo', '0014_añadirusuarios_ultimoacceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NoSeQuePedo.AñadirUsuarios'),
        ),
    ]
