# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoSeQuePedo', '0016_auto_20171129_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
